name: cleanup
on: workflow_dispatch

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Remove build artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 minute'
